env:
  global:
    - PYINSTALLER_COMMIT=3010fdfaa037e9b19e936711d0c0be9b314b03c6

jobs:
  include:
    - os: windows
      name: "Windows LONG foldername VC 14"
      language: shell
      env:
        - vcver="14.0"
    - os: windows
      name: "Windows SHORT foldername VC 14"
      language: shell
      env:
        - shortpath="yes"
        - vcver="14.0"
    - os: windows
      name: "Windows LONG foldername VC 2017"
      language: shell
      env:
        - vcver="15.0"
    - os: windows
      name: "Windows SHORT foldername VC 2017"
      language: shell
      env:
        - shortpath="yes"
        - vcver="15.0"

before_install:
  - choco install python --version=3.7.7
  - if [[ "${vcver}" == "14.0" ]]; then
      choco install vcbuildtools;
    fi

install:
  - wget --quiet https://github.com/pyinstaller/pyinstaller/archive/$PYINSTALLER_COMMIT.tar.gz
  - tar xf $PYINSTALLER_COMMIT.tar.gz
  - if [[ -v shortpath ]]; then
      mv pyinstaller-$PYINSTALLER_COMMIT /c/pyinstaller;
      cd /c/pyinstaller/bootloader;
    else
      cd pyinstaller-$PYINSTALLER_COMMIT/bootloader;
    fi
  - pwd
  - /c/Python37/python.exe ./waf all --msvc_version " msvc ${vcver}"
  - /c/Python37/python.exe setup.py install
  - /c/Python37/bin/pyinstaller.exe hello-world.py
