env:
  global:
    - PYINSTALLER_COMMIT=3010fdfaa037e9b19e936711d0c0be9b314b03c6

jobs:
  include:
    - os: windows
      name: "Windows LONG foldername VC 2015"
      language: shell
      env:
        - vcver="14.0"
    - os: windows
      name: "Windows SHORT foldername VC 2015"
      language: shell
      env:
        - shortpath="yes"
        - vcver="14.0"
    - os: windows
      name: "Windows LONG foldername VC 2017"
      language: shell
      env:
        - vcver="15.0"
    - os: windows
      name: "Windows SHORT foldername VC 2017"
      language: shell
      env:
        - shortpath="yes"
        - vcver="15.0"

before_install:
  - choco install python --version=3.7.7
  - if [[ "${vcver}" == "14.0" ]]; then
      choco install vcbuildtools;
    fi

install:
  - mypath=$(pwd)
  - wget --quiet https://github.com/pyinstaller/pyinstaller/archive/$PYINSTALLER_COMMIT.tar.gz
  - tar xf $PYINSTALLER_COMMIT.tar.gz
  - if [[ -v shortpath ]]; then
      mv pyinstaller-$PYINSTALLER_COMMIT /c/pyinstaller;
      cd /c/pyinstaller/bootloader;
    else
      cd pyinstaller-$PYINSTALLER_COMMIT/bootloader;
    fi
  - pwd
  - /c/Python37/python.exe ./waf all --msvc_version "msvc ${vcver}"
  - BOOTLOADER_SUCCESS=$?
  - cat build/config.log
  - if [ $BOOTLOADER_SUCCESS -ne 0 ]]; then
      false;
    fi
  - cd ..
  - /c/Python37/python.exe setup.py install
  - cd $mypath
  - /c/Python37/python.exe -m PyInstaller hello-world.py
  - dist/hello-world/hello-world.exe
