env:
  global:
    - PYINSTALLER_COMMIT=3010fdfaa037e9b19e936711d0c0be9b314b03c6

jobs:
  include:
    - os: windows
      name: "Windows LONG foldername VC 14"
      language: shell
      env:
        - vc14="yes"
    - os: windows
      name: "Windows SHORT foldername VC 14"
      language: shell
      env:
        - shortpath="yes"
        - vc14="yes"
    - os: windows
      name: "Windows LONG foldername VC 2017"
      language: shell
    - os: windows
      name: "Windows SHORT foldername VC 2017"
      language: shell
      env:
        - shortpath="yes"
     

before_install:
  - choco install python --version=3.7.7
  - if [[ -v vc14 ]]; then
      choco install vcbuildtools;
      wafopts='--msvc_version "msvc 14.0"';
    fi

install:
  - wget --quiet https://github.com/pyinstaller/pyinstaller/archive/$PYINSTALLER_COMMIT.tar.gz
  - tar xf $PYINSTALLER_COMMIT.tar.gz
  - if [[ -v shortpath ]]; then
      mv pyinstaller-$PYINSTALLER_COMMIT pyinstaller;
      cd pyinstaller/bootloader;
    else
      cd pyinstaller-$PYINSTALLER_COMMIT/bootloader;
    fi
  - pwd
  - /c/Python37/python.exe ./waf all $wafopts
  - /c/Python37/python.exe setup.py install
  - /c/Python37/bin/pyinstaller.exe hello-world.py
  
