name: Build and test

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - 'wiki/**'
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-13
          #- macos-14
          #- macos-15
          #- macos-latest
          #- ubuntu-22.04
          #- ubuntu-24.04
          #- ubuntu-latest
          #- ubuntu-24.04-arm
          #- ubuntu-22.04-arm
          #- windows-11-arm
          - windows-2019
          #- windows-2022
          #- windows-2025
          #- windows-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: Windows Install rust
      if: runner.os == 'Windows'
      run: |
        choco install rust

    - name: Build wheels
      run: |
        git clone https://github.com/lxml/lxml.git
        git clone https://github.com/pyca/cryptography.git
        python3 -m pip install cibuildwheel
        export CIBW_BUILD="cp313-win_arm64"
        cd lxml
        python3 -m cibuildwheel --output-dir wheelhouse
        cd ../cryptography
        python3 -m cibuildwheel --output-dir wheelhouse
