name: Build and test

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        
    steps:

      # actions/checkout MUST come before auth
    - uses: actions/checkout@v3
    
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/318417991012/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider
        service_account: github-actions@gha-hello-world.iam.gserviceaccount.com
        token_format: access_token
        
    - name: Get info about Google service account access
      run: |
        python3 -m pip install google-auth
        python3 -m pip install requests
        python3 src/test.py
