name: GitHub Actions Hello World

on: [push, pull_request]

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ubuntu-18.04

    steps:

      - name: Download OpenSSL
        run: |
          cd "${HOME}"
          url="https://www.openssl.org/source/openssl-1.1.1l.tar.gz"
          echo "Downloading ${url}..."
          curl -o openssl.tar.gz -s "${url}"

      - name: Extracting OpenSSL
        run: |
          cd "${HOME}"
          tar xf openssl.tar.gz
          mv openssl-*/ openssl/

      - name: Config OpenSSL
        run: |
          cd ~
          OPENSSL_INSTALL_DIR=~/ssl
          mkdir "${OPENSSL_INSTALL_DIR}"
          PYTHON_INSTALL_DIR=~/python
          mkdir "${PYTHON_INSTALL_DIR}"
          echo "PYTHON_INSTALL_DIR=${PYTHON_INSTALL_DIR}" >> $GITHUB_ENV
          echo "PATH=$PYTHON_INSTALL_DIR/bin:$OPENSSL_INSTALL_DIR/bin:${PATH}" >> $GITHUB_ENV
          OPENSSL_SOURCE_DIR=~/openssl
          cd $OPENSSL_SOURCE_DIR
          echo "OPENSSL_SOURCE_DIR=${OPENSSL_SOURCE_DIR}" >> $GITHUB_ENV
          echo "OPENSSL_INSTALL_DIR=${OPENSSL_INSTALL_DIR}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${HOME}/python/lib" >> $GITHUB_ENV
          ./config shared --prefix="${HOME}/ssl"

      - name: Make OpenSSL
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          make

      - name: Install OpenSSL
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          make install

      - name: Run OpenSSL
        run: |
          "${OPENSSL_INSTALL_DIR}/bin/openssl" version

      - name: Download Python
        run: |
          cd "${HOME}"
          git clone https://github.com/python/cpython.git
          cd cpython
          git checkout v3.9.7
          PYTHON_SOURCE_DIR=$(pwd)
          echo "PYTHON_SOURCE_DIR=${PYTHON_SOURCE_DIR}" >> $GITHUB_ENV

      - name: Configure Python
        run: |
          cd "${PYTHON_SOURCE_DIR}"
          ./configure --with-openssl-rpath=auto \
                      --with-openssl="${OPENSSL_INSTALL_DIR}" \
                      --enable-shared \
                      --prefix="${PYTHON_INSTALL_DIR}" \
                      --with-ensurepip=upgrade \
                      --enable-optimizations \
                      --with-lto
      - name: Build Python
        run: |
          cd "${PYTHON_SOURCE_DIR}"
          make
          
      - name: Install Python
        run: |
          cd "${PYTHON_SOURCE_DIR}"
          make install
  
      - name: Run Python
        run: |
          "${PYTHON_INSTALL_DIR}/bin/python3" -c "import platform; import ssl; print(f'Python {platform.python_version()} {ssl.OPENSSL_VERSION}')"
