name: GitHub Actions Hello World

on: [push, pull_request]

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-2022

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache builds
        id: cache-builds
        uses: actions/cache@v3
        with:
          path: |
            zeros-*
          key: ${{ matrix.os }}-20220902

      - name: Generate zeros
        if: steps.cache-builds.outputs.cache-hit != 'true'
        env:
          os: ${{ matrix.os }}
        run: |
          for i in {000000..999999}; do echo 0 >> "zeros-${os}.txt"; done
