name: Build and test

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04, windows-latest, macos-13]
        python-version: ["3.12"]
        
    steps:

      # actions/checkout MUST come before auth
    - uses: actions/checkout@v3

    - id: uname
      name: Run uname command
      run: |
        uname -a

    - id: set-cmd
      name: Run set command
      run: |
        set

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/318417991012/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider
        service_account: github-actions@gha-hello-world.iam.gserviceaccount.com
        token_format: access_token
        
    - name: Configure Python venv
      run: |
        python3 -m venv myvenv
        if [[ "${RUNNER_OS}" == "Windows" ]]; then
            myvenv/Scripts/activate
            python="python3"
        else
            python="myvenv/bin/python3"
        fi
        echo "python=${python}" >> $GITHUB_ENV

    - name: Install pip packages
      run: |
        $python -m pip install google-auth requests

    - name: USE GOOGLE SERVICES
      run: |
        $python src/test.py
