name: Build and test

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  py:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macos-11, macos-12]
        
    steps:

      - uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install GAM
        run: |
          bash <(curl -s -S -L https://gam-shortn.appspot.com/gam-install)
