name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 * * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.5"
  MIN_PYTHON_VERSION: "3.9.5"
  BUILD_OPENSSL_VERSION: "1.1.1k"
  MIN_OPENSSL_VERSION: "1.1.1k"
  PYINSTALLER_VERSION: "98aa4508455f3baaa8f15754ae5c95ee0e32806e"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest

    steps:

      - name: Hello World
        run: |
                set
                export python=python3
                export pip=pip3
                if [ "${ImageOS:0:5}" == "macos" ]; then
                    export pyfile=python-$BUILD_PYTHON_VERSION-macos11.pkg
                    curl -o $pyfile https://www.python.org/ftp/python/$BUILD_PYTHON_VERSION/$pyfile
                    echo "installing Python $BUILD_PYTHON_VERSION..."
                    sudo installer -pkg ./$pyfile -target /
                    export python=/usr/local/bin/python3
                    export pip=/usr/local/bin/pip3
                elif [ "${ImageOS:0:3}" == "win" ]; then
                    export pyfile=python-$BUILD_PYTHON_VERSION-embed-amd64.zip
                    curl -o $pyfile https://www.python.org/ftp/python/$BUILD_PYTHON_VERSION/$pyfile
                    echo "Unpacking Embedded Python..."
                    7z e $pyfile -oc:\python
                    ls -l c:/python
                    export python=/c/python/python.exe
                    export pip='/c/python/python.exe -m pip'
                    export PATH=/c/python/Scripts:$PATH
                fi
                $python -V
                curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
                $python get-pip.py
                $pip -V
                $pip install git+git://github.com/pyinstaller/pyinstaller.git@$PYINSTALLER_VERSION
                echo -e "from platform import machine\n\nprint(f'Hello {machine()}')" > helloarch.py
                $python -OO -m PyInstaller --clean --noupx --strip helloarch.py
                ls -al dist/
                ls -al dist/helloarch/
                du -sch dist/helloarch
                dist/helloarch/helloarch
