name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 1 * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.7"
  MIN_PYTHON_VERSION: "3.9.7"
  BUILD_OPENSSL_VERSION: "3.0.0"
  MIN_OPENSSL_VERSION: "1.1.1l"
  PYINSTALLER_VERSION: "5a02f55c696f16b98f23a8b487f3daa8f644a8d2"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
          - os: macos-10.15
          - os: windows-latest

    steps:
      - name: Install Strawberry Perl on Win
        runs-on: 'windows-latest'
        run: |
          choco install strawberryperl
          
      - name: Download OpenSSL
        run: |
          url="https://www.openssl.org/source/openssl-${BUILD_OPENSSL_VERSION}.tar.gz"
          echo "Downloading ${url}..."
          curl -o openssl.tar.gz -s "${url}"

      - name: Extracting OpenSSL
        run: |
          tar xvvf openssl.tar.gz
          
      - name: Compile OpenSSL
        run: |
          mkdir "${HOME}/ssl"
          cd openssl-*
          ./config shared --prefix="${HOME}/ssl"
          make
          
      - name: Install OpenSSL
        run: |
          cd openssl-*
          make install
