name: Build and test

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash
on:
  push:

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:

    # actions/checkout MUST come before auth
    - uses: actions/checkout@v3
    
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: projects/318417991012/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider
        service_account: github-actions@gha-hello-world.iam.gserviceaccount.com
        
    - name: Get info about Google service account access
      run: |
        pip install google-auth
        pip install requests
        python3 test.py
