name: Build and test

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - 'wiki/**'
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-11-arm
          - windows-2022
          - windows-2025
          - windows-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: run stuff
      env:
        cid: ${{ job.container.id }}
        services: ${{ job.services }}
        stat: ${{ job.status }}
        run_num: ${{ github.run_number }}
        run_att: ${{ github.run_attempt }}
      run: |
        python3 -m venv venv
        dir venv
        dir venv/bin
        venv/bin/pip install --upgrade pyinstaller
        echo "print('Hello World.')" > helloworld.py
        venv/bin/pyinstaller --onefile helloworld.py
        file dist/helloworld*
        dist/helloworld
        
    - name: Install Certum MSI
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $url = "https://files.certum.eu/software/SimplySignDesktop/Windows/9.3.1.66/SimplySignDesktop-9.3.1.66-64-bit-pl.msi"
        $file = "SimplySignDesktop-9.3.1.66-64-bit-pl.msi" 
        Invoke-WebRequest $url -OutFile $file
        $log = "install.log" 
        $procMain = Start-Process "msiexec" "/i `"$file`" /qn /l*! `"$log`"" -NoNewWindow -PassThru
        $procLog = Start-Process "powershell" "Get-Content -Path `"$log`" -Wait" -NoNewWindow -PassThru 
        $procMain.WaitForExit() 
        $procLog.Kill()

    - name: Install oathtool
      if: runner.os == 'Windows'
      run: |
        choco install -y oathtool

    - name: Generate OTP and Login
      if: runner.os == 'Windows'
      env:
          TOTP_SECRET: ${{ secrets.TOTP_SECRET }}
      run: |
        oathtool --totp=SHA256 --base32 "$TOTP_SECRET"
