name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 1 * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.7"
  BUILD_OPENSSL_VERSION: "3.0.0"
  PYINSTALLER_VERSION: "5a02f55c696f16b98f23a8b487f3daa8f644a8d2"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-16.04
          - os: macos-10.15
          - os: windows-latest

    steps:

      - name: Download OpenSSL
        run: |
          cd "${HOME}"
          url="https://www.openssl.org/source/openssl-${BUILD_OPENSSL_VERSION}.tar.gz"
          echo "Downloading ${url}..."
          curl -o openssl.tar.gz -s "${url}"

      - name: Extracting OpenSSL
        run: |
          cd "${HOME}"
          tar xf openssl.tar.gz

      - name: Config OpenSSL
        if: matrix.os != 'windows-latest'
        run: |
          mkdir "${HOME}/ssl"
          cd "${HOME}/openssl-${BUILD_OPENSSL_VERSION}"
          OPENSSL_SOURCE_DIR=$(pwd)
          MAKE=make
          echo "OPENSSL_SOURCE_DIR=${OPENSSL_SOURCE_DIR}" >> $GITHUB_ENV
          echo "MAKE=${MAKE}" >> $GITHUB_ENV
          ./config shared --prefix="${HOME}/ssl"

      - name: Config Windows OpenSSL
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          choco install nasm
          cd ~
          New-Item -Path "~" -Name ssl -ItemType "directory"
          $env:ssl_install = Resolve-Path -Path "$HOME/ssl"
          cd "openssl-$env:BUILD_OPENSSL_VERSION"
          OPENSSL_SOURCE_DIR=$(pwd)
          $ENV:PATH="$ENV:PATH;c:\Program Files\NASM\"
          MAKE=nmake
          cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && set > %temp%\vcvars.txt'
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object {
           if ($_ -match "^(.*?)=(.*)$") {
             Set-Content "env:\$($matches[1])" $matches[2]
             Add-Content -Path $env:GITHUB_ENV -Value "$($matches[1])=${env:$matches[2]}"
           }
          }
          perl Configure VC-WIN64A shared --prefix="$env:ssl_install"
          
      - name: Make OpenSSL
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          $MAKE

      - name: Install OpenSSL
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          $MAKE install

      - name: Run OpenSSL
        run: |
          LD_LIBRARY_PATH="${HOME}/ssl/lib64"
          $HOME/ssl/bin/openssl version


