name: Build and test

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-24.04-aarch64
          - ubuntu-latest
          - windows-2019
          - windows-2022
          - windows-latest
          - windows-aarch64
        
    steps:
    - uses: actions/checkout@v4
    - name: Uname
      run: |
        uname -a
    
