name: Build and test

permissions:
  contents: 'read'
  id-token: 'write'

on:
  push:
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  py:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:

    # actions/checkout MUST come before auth
    - uses: 'actions/checkout@v3'
    
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@latest'
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/318417991012/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider'
        service_account: 'github-actions@gha-hello-world.iam.gserviceaccount.com'

    - name: 'Access secret'
      run: |
        curl https://oauth2.googleapis.com/tokeninfo \
          --header "Authorization: Bearer ${{ steps.auth.outputs.access_token }}"
