name: GitHub Actions Hello World

on: [push, pull_request]

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-2022

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache builds
        id: cache-builds
        uses: actions/cache@v3
        with:
          path: |
            data-*
          key: ${{ matrix.os }}-20220902-01

      - name: Generate data
        if: steps.cache-builds.outputs.cache-hit != 'true'
        env:
          os: ${{ matrix.os }}
        run: |
          curl -o "data-${os}" https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_14816.131.0_eve_recovery_stable-channel_mp-v2.bin.zip
