name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 1 * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.7"
  MIN_PYTHON_VERSION: "3.9.7"
  BUILD_OPENSSL_VERSION: "3.0.0"
  MIN_OPENSSL_VERSION: "1.1.1l"
  PYINSTALLER_VERSION: "5a02f55c696f16b98f23a8b487f3daa8f644a8d2"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
          - os: macos-10.15
          - os: windows-latest

    steps:

      - name: Download OpenSSL
        run: |
          url="https://www.openssl.org/source/openssl-${BUILD_OPENSSL_VERSION}.tar.gz"
          echo "Downloading ${url}..."
          curl -o openssl.tar.gz -s "${url}"

      - name: Extracting OpenSSL
        run: |
          tar xvvf openssl.tar.gz
          
      - uses: actions/checkout@v2
      
      - uses: shogo82148/actions-setup-perl@v1
        with:
          distribution: strawberry
      
      - name: Config OpenSSL
        run: |
          mkdir "${HOME}/ssl"
          cd openssl-${BUILD_OPENSSL_VERSION}
          ./config shared --prefix="${HOME}/ssl"
      
      - name: Make OpenSSL
        run: |
          cd openssl-${BUILD_OPENSSL_VERSION}
          make
          
      - name: Install OpenSSL
        run: |
          cd openssl-${BUILD_OPENSSL_VERSION}
          make install
