name: Build and test

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - 'wiki/**'
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          #- macos-13
          #- macos-14
          #- macos-15
          #- macos-latest
          #- ubuntu-22.04
          #- ubuntu-24.04
          #- ubuntu-latest
          #- ubuntu-24.04-arm
          #- ubuntu-22.04-arm
          #- windows-11-arm
          - windows-2019
          #- windows-2022
          #- windows-2025
          #- windows-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: Install rust
      run: |
        choco install rust

    - name: git clone
      run: |
        git clone https://github.com/jay0lee/lxml.git
        git clone https://github.com/pyca/cryptography.git
        cd lxml
        python3 -m pip install cibuildwheel
        cibuildwheel --print-build-identifiers --platform windows

    - name: Build wheels
      uses: pypa/cibuildwheel@v2.23.2
      with:
        only: cp313_win-arm64
        package-dir: lxml
