name: GitHub Actions Hello World

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            mid: 0
          - os: macos-10.15
            mid: 1
          - os: windows-latest
            mid: 2

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Windows install newer Python (needed for building Python)
        uses: actions/setup-python@v2
        if: matrix.os == 'windows-latest'
        with:
          python-version: "3.10"
          
      - name: Cache Python build
        id: cache-python
        uses: actions/cache@v2
        with:
          path: |
            ~/python
            ~/cpython
            ~/ssl
            ~/openssl
          key: ${{ matrix.os }}-${{ matrix.mid }}-20211102-01

      - name: Bash Env Variables
        run: |
          cd "${HOME}"
          mkdir -p ssl
          mkdir -p python
          OPENSSL_INSTALL_DIR="${HOME}/ssl"
          OPENSSL_SOURCE_DIR="${HOME}/openssl"
          PYTHON_INSTALL_DIR="${HOME}/python"
          PYTHON_SOURCE_DIR="${HOME}/cpython"
          echo "OPENSSL_SOURCE_DIR=${OPENSSL_SOURCE_DIR}" >> $GITHUB_ENV
          echo "OPENSSL_INSTALL_DIR=${OPENSSL_INSTALL_DIR}" >> $GITHUB_ENV
          echo "PYTHON_SOURCE_DIR=${PYTHON_SOURCE_DIR}" >> $GITHUB_ENV
          echo "PYTHON_INSTALL_DIR=${PYTHON_INSTALL_DIR}" >> $GITHUB_ENV
          echo "LD_LIBRARY_PATH=${OPENSSL_INSTALL_DIR}/lib:${PYTHON_INSTALL_DIR}/lib" >> $GITHUB_ENV
          echo "PYTHON=${PYTHON_INSTALL_DIR}/bin/python3" >> $GITHUB_ENV

      - name: PowerShell Env Variables
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "PS_OPENSSL_INSTALL_DIR=$HOME\ssl"
          Add-Content -Path $env:GITHUB_ENV -Value "PS_OPENSSL_SOURCE_DIR=$HOME\openssl"
          Add-Content -Path $env:GITHUB_ENV -Value "PS_PYTHON_INSTALL_DIR=$HOME\python"
          Add-Content -Path $env:GITHUB_ENV -Value "PS_PYTHON_SOURCE_DIR=$HOME\cpython"
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON=$env:PYTHON_SOURCE_DIR/release/amd64/binaries/python.exe"

      - name: Get latest stable OpenSSL source
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${HOME}"
          git clone https://github.com/openssl/openssl.git
          cd openssl
          export latest_stable=$(git tag --list openssl-* | grep -v alpha | grep -v beta | sort -Vr | head -n1)
          git checkout "${latest_stable}"

      - name: Unix Config OpenSSL
        if: matrix.os != 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${HOME}"
          cd "${OPENSSL_SOURCE_DIR}"
          echo "MAKE=make" >> $GITHUB_ENV
          echo "OPENSSL_MAKE_OPTS=-j$(nproc)" >> $GITHUB_ENV
          ./Configure --libdir=lib --prefix="${OPENSSL_INSTALL_DIR}"

      - name: Windows Config OpenSSL
        if: matrix.os == 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          choco install nasm
          $env:PATH="$ENV:PATH;c:\Program Files\NASM\"
          cmd /c 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && set MAKE=nmake && set > %temp%\vcvars.txt'
          Get-Content "$env:temp\vcvars.txt" | Foreach-Object {
           if ($_ -match "^(.*?)=(.*)$") {
             Set-Content "env:\$($matches[1])" $matches[2]
             Add-Content -Path $env:GITHUB_ENV -Value "$($matches[1])=$($matches[2])"
           }
          }
          pwd
          echo $env:PS_OPENSSL_SOURCE_DIR
          cd $env:PS_OPENSSL_SOURCE_DIR
          pwd
          perl ./Configure VC-WIN64A --prefix="$env:PS_OPENSSL_INSTALL_DIR"

      - name: Rename GNU link on Windows
        if: matrix.os == 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        shell: bash
        run: mv /usr/bin/link /usr/bin/gnulink

      - name: Make OpenSSL
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          $MAKE $OPENSSL_MAKE_OPTS

      - name: Install OpenSSL
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${OPENSSL_SOURCE_DIR}"
          $MAKE install

      - name: Run OpenSSL
        run: |
          "${OPENSSL_INSTALL_DIR}/bin/openssl" version

      - name: Get latest stable Python source
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${HOME}"
          git clone https://github.com/python/cpython.git
          cd cpython
          PYTHON_SOURCE_DIR=$(pwd)
          export latest_stable=$(git tag --list | grep -v a | grep -v rc | grep -v b | sort -Vr | head -n1)
          git checkout "${latest_stable}"
          echo "PYTHON_SOURCE_DIR=${PYTHON_SOURCE_DIR}" >> $GITHUB_ENV

      - name: Mac/Linux Configure Python
        if: matrix.os != 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        run: |
          export PYTHON_INSTALL_DIR="${HOME}/python"
          mkdir -p "${PYTHON_INSTALL_DIR}"
          echo "PYTHON_INSTALL_DIR=${PYTHON_INSTALL_DIR}" >> $GITHUB_ENV
          cd "${PYTHON_SOURCE_DIR}"
          ./configure --with-openssl="${OPENSSL_INSTALL_DIR}" \
                      --prefix="${PYTHON_INSTALL_DIR}" \
                      --enable-shared \
                      --with-ensurepip=upgrade \
                      --enable-optimizations \
                      --with-lto

      - name: Windows Config/Build/Install Python
        if: matrix.os == 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          cd $env:PS_PYTHON_SOURCE_DIR
          $env:PYTHON = (gcm python).Path
          $env:PIP = (gcm pip).Path
          $env:PYTHONPATH = Resolve-Path -Path $env:PYTHON\..
          echo "PYTHONPATH: $env:PYTHONPATH"
          Invoke-Expression "$env:PYTHON -V"
          Invoke-Expression "$env:PIP install --upgrade --user pip"
          Invoke-Expression "$env:PIP install --upgrade --user sphinx"
          $env:SPHINXBUILD = (gcm sphinx-build).Path
          echo "Sphinx Build location: $env:SPHINXBUILD"
          Invoke-Expression "$env:SPHINXBUILD --version"
          Add-Content -Path $env:GITHUB_ENV -Value "SPHINXBUILD=${env:SPHINXBUILD}"
          $env:DefaultWindowsSDKVersion = "10.0.20348.0"
          PCBuild\get_externals.bat
          echo "delete..."
          Get-ChildItem -Path externals\openssl-bin-1.1.1l\amd64\ -Include *.* -File -Recurse | foreach { $_.Delete()}
          echo "copy..."
          cp "$HOME\ssl\lib\*" externals\openssl-bin-1.1.1l\amd64\
          cp "$HOME\ssl\bin\*" externals\openssl-bin-1.1.1l\amd64\
          echo "ls afterwards..."
          ls externals\openssl-bin-1.1.1l\amd64
          echo "ssl/include"
          gci -r -Path "$HOME/ssl/include" | select -exp FullName
          cp "$HOME\ssl\include\openssl\*" externals\openssl-bin-1.1.1l\amd64\include\openssl\
          cp "$HOME\ssl\include\openssl\applink.c" externals\openssl-bin-1.1.1l\amd64\include\
          echo "INCLUDE OPENSSL"
          gci -r -Path externals\openssl-bin-1.1.1l\amd64\include\openssl\ | select -exp FullName
          cp "$env:GITHUB_WORKSPACE/openssl.props" PCBuild\
          gci -r -Path PCBuild\ | select -exp FullName
          Tools\msi\buildrelease.bat -x64 --out release --skip-msi --skip-nuget
          echo "In release:"
          dir release\
          dir release\amd64\
          dir release\amd64\binaries\
          $env:PYTHON = Resolve-Path -Path release\amd64\binaries\python.exe
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON=${env:PYTHON}"

      - name: Mac/Linux Build Python
        if: matrix.os != 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${PYTHON_SOURCE_DIR}"
          $MAKE -j$(nproc)
          
      - name: Mac/Linux Install Python
        if: matrix.os != 'windows-latest' && steps.cache-python.outputs.cache-hit != 'true'
        run: |
          cd "${PYTHON_SOURCE_DIR}"
          $MAKE install

      - name: Run Python
        run: |
          "${PYTHON}" helloworld.py
          
      - name: Upgrade pip, wheel, etc
        run: |
          curl -O https://bootstrap.pypa.io/get-pip.py
          "${PYTHON}" get-pip.py
          "${PYTHON}" -m pip install --upgrade pip
          "${PYTHON}" -m pip install --upgrade wheel
          "${PYTHON}" -m pip install --upgrade setuptools

      - name: Install PyInstaller
        run: |
             git clone https://github.com/pyinstaller/pyinstaller.git
             cd pyinstaller
             export latest_release=$(git tag --list | grep -v dev | grep -v rc | sort -Vr | head -n1)
             git checkout "${latest_release}"
             # remove pre-compiled bootloaders so we fail if bootloader compile fails
             rm -rf PyInstaller/bootloader/*-*/*
             cd bootloader
             export DefaultWindowsSDKVersion="10.0.20348.0"
             export TARGETARCh=$($PYTHON -c 'import struct; print(struct.calcsize("P")*8)')bit
             $python ./waf all --target-arch=$TARGETARCH
             cat build/config.log
             cd ..
             "${PYTHON}" -m pip install .

      - name: Compile helloworld with PyInstaller
        run: |
          "${PYTHON}" -OO -m PyInstaller -F helloworld.py
          
      - name: Run PyInstaller-compiled helloworld
        run: dist/helloworld

      - name: Linux install patchelf/staticx
        if: matrix.os == 'ubuntu-20.04'
        run: |
          "${PYTHON}" -m pip install --upgrade patchelf-wrapper
          "${PYTHON}" -m pip install --upgrade staticx

      - name: Linux Make Static helloworld
        if: matrix.os == 'ubuntu-20.04'
        run: |
          "${PYTHON_INSTALL_DIR}/bin/python3" -m staticx dist/helloworld dist/helloworld-staticx
          
      - name: Linux Run StaticX-ed helloworld
        if: matrix.os == 'ubuntu-20.04'
        run: dist/helloworld-staticx

      - name: Archive artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: helloworld-binaries ${{ matrix.mid }}
          path: dist/helloworld*
