name: GitHub Actions Hello World

on: [push, pull_request]

defaults:
  run:
    shell: bash
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-2022

    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Cache builds
        id: cache-builds
        uses: actions/cache@v3
        with:
          path: |
            data/*
          key: ${{ matrix.os }}-20220902-02

      - name: Generate data
        if: steps.cache-builds.outputs.cache-hit != 'true'
        env:
          os: ${{ matrix.os }}
        run: |
          mkdir data
          cd data
          count=0
          for a in {0..9}; do
            for b in {00..99}; do
              for c in {00..99}; do
                mydir="${a}/${b}/${c}"
                myfile="${mydir}/data"
                echo $myfile
                mkdir -p $mydir
                echo "xyz" > $myfile
                count=$((count + 1))
              done
            done
          done
          echo "Created ${count} files..."
