name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 * * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.5"
  MIN_PYTHON_VERSION: "3.9.5"
  BUILD_OPENSSL_VERSION: "1.1.1k"
  MIN_OPENSSL_VERSION: "1.1.1k"
  PYINSTALLER_VERSION: "98aa4508455f3baaa8f15754ae5c95ee0e32806e"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
          - os: ubuntu-18.04
          - os: ubuntu-20.04
          - os: macos-10.15
          - os: macos-11.0
          - os: windows-2019
          - os: windows-2016

    steps:

      #      - name: Use pre-compiled Python for testing
      #  uses: actions/setup-python@v2
      #  with:
      #    python-version: 3.9.5
          
      - name: Hello World
        run: |
                set
                python3 -V
                pip3 install git+git://github.com/pyinstaller/pyinstaller.git@$PYINSTALLER_VERSION
                echo -e "from platform import machine\n\nprint(f'Hello {machine()}')" > helloarch.py
                python3 -OO -m PyInstaller --clean --noupx --strip helloarch.py
                ls -al dist/
                ls -al dist/helloarch/
                dist/helloarch/helloarch
