name: GitHub Actions Hello World

on:
  push:
  pull_request:
  schedule:
    - cron: '30 20 1 * *'

defaults:
  run:
    shell: bash

env:
  BUILD_PYTHON_VERSION: "3.9.7"
  BUILD_OPENSSL_VERSION: "3.0.0"
  PYINSTALLER_VERSION: "5a02f55c696f16b98f23a8b487f3daa8f644a8d2"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-16.04
          - os: macos-10.15
          - os: windows-latest

    steps:

      - name: Download OpenSSL
        run: |
          cd "${HOME}"
          url="https://www.openssl.org/source/openssl-${BUILD_OPENSSL_VERSION}.tar.gz"
          echo "Downloading ${url}..."
          curl -o openssl.tar.gz -s "${url}"

      - name: Extracting OpenSSL
        run: |
          cd "${HOME}"
          tar xvvf openssl.tar.gz
          pwd

      - name: Config OpenSSL
        if: matrix.os != 'windows-latest'
        run: |
          mkdir "${HOME}/ssl"
          cd "${HOME}/openssl-${BUILD_OPENSSL_VERSION}"
          ./config shared --prefix="${HOME}/ssl"

      - name: Config Windows OpenSSL
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          cd ~
          Set-Variable -Name env:ssl_install -Value "$HOME/ssl"
          mkdir $env:ssl_install
          cd "openssl-$env:BUILD_OPENSSL_VERSION"
          perl Configure VC-WIN64A shared --prefix="$env:ssl_install"
          
      - name: Make OpenSSL
        run: |
          cd "${HOME}/openssl-${BUILD_OPENSSL_VERSION}"
          make

      - name: Install OpenSSL
        run: |
          cd "${HOME}/openssl-${BUILD_OPENSSL_VERSION}"
          make install
