name: Build and test

permissions:
  contents: write

defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - 'wiki/**'
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-11-arm
          - windows-2019
          - windows-2022
          - windows-2025
          - windows-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: run stuff
      env:
        cid: ${{ job.container.id }}
        services: ${{ job.services }}
        stat: ${{ job.status }}
        run_num: ${{ github.run_number }}
        run_att: ${{ github.run_attempt }}
      run: |
        echo "HOME: ${HOME}"
        set
        uname -a
        whoami

    - name: Install Certum MSI
      if: runner.os == 'Windows'
      run: |
        curl -O https://files.certum.eu/software/SimplySignDesktop/Windows/9.3.1.66/SimplySignDesktop-9.3.1.66-64-bit-pl.msi
        msiexec /quiet /norestart /package SimplySignDesktop-9.3.1.66-64-bit-pl.msi
