name: Build and test

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  push:
    paths-ignore:
      - 'wiki/**'
  pull_request:
  schedule:
    - cron: '37 22 * * *'

jobs:
  gha:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
          - macos-latest
          - ubuntu-22.04
          - ubuntu-24.04
          - ubuntu-latest
          - ubuntu-24.04-arm
          - ubuntu-22.04-arm
          - windows-11-arm
          - windows-2019
          - windows-2022
          - windows-2025
          - windows-latest
        
    steps:
    - uses: actions/checkout@v4

    - name: existing Python
      run: |
        which python3
        python -V
        python -c "import platform; print(platform.machine())"
        export runner_os=$(echo "$RUNNER_OS" | tr '[:upper:]' '[:lower:]')

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12' 

    - name: Uname
      run: |
        uname -a

    - name: new Python
      run: |
        which python3
        python -V
        python -c "import platform; print(platform.machine())"
    
