name: Push wiki
permissions:
  contents: read
on:
  push:
    paths:
      - wiki
jobs:
  pushwiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Uname
        run: |
          uname -a
