name: Build Executable
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.14.3, 3.14.4]
        mpmethod: [fork, forkserver, spawn]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install PyInstaller
        run: |
          pip install pyinstaller

      - name: run python script
        env:
          mpmethod: ${{ matrix.mpmethod }}
        run: python3 multiprocess-hw.py --method "$mpmethod"

      - name: Build with PyInstaller
        run: pyinstaller multiprocess-hw.py

      - name: Run pyinstaller app
        env:
          mpmethod: ${{ matrix.mpmethod }}
        run: dist/multiprocess-hw/multiprocess-hw --method "$mpmethod"
