name: Build Executable
on: [push]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: [3.14.3, 3.14.4]
        pyinst: ["pyinstaller", "git+https://github.com/pyinstaller/pyinstaller"]
        mpmethod: [fork, forkserver, spawn]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: run python script
        env:
          mpmethod: ${{ matrix.mpmethod }}
        run: python3 multiprocess-hw.py --method "$mpmethod"

      - name: Install PyInstaller
        env:
          pyinst: ${{ matrix.pyinst }}
        run: |
          pip install "$pyinst"

      - name: Build with PyInstaller
        run: pyinstaller multiprocess-hw.py

      - name: Run pyinstaller app
        env:
          mpmethod: ${{ matrix.mpmethod }}
        run: dist/multiprocess-hw/multiprocess-hw --method "$mpmethod"
